- menu_name: "Services"

- name: "Change Management"
  url: "/02ocm/"
  title: "Find Out More About Change Management"

- name: "Communication"
  url: "/03com/"
  title: "Find Out More About Communication"

- name: "Instructional Design"
  url: "/04insd/"
  title: "Find Out More About Instructional Design"

- name: "Contact"
  url: "/contact/"
  title: "Contact Mojo-Web"

#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
